### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by BinaryWorld0101201** [fingerguns83/PHPTwitchBot#1]
How run? php twitchclient.php don't give response

**Comment by fingerguns83** [comment]
This is just a background service, nothing will print to the console. I personally just run it in a screen session and then detach.

If you want to log received data to STDOUT, you'd need to add
`$output = new React\Stream\WritableResourceStream(STDOUT, $loop);`
before the connection is made and then
`$output->write($data);`
in the "$connection->on('data'..." callback.

I'll add CLI interactions for debugging, logging, etc. to the to-do list.
